function INTRO_CLASS_IMAGERY(SUBJECT, SUBJ_NAME, SESSION, ROUND)

%SETUP 
class_SETUP; 

% present experiment summary
start_time = GetSecs;
instruct = ['You will now begin the second half of the experiment. \n\n' ...
    'In this half, you will be presented with the same images as before,'...
    'following the same basic procedure of one image trial being followed by three iterations of the number task.'...
    '\n\n However, ']; 
DrawFormattedText(mainWindow,instruct,'center','center',COLORS.MAINFONTCOLOR,WRAPCHARS);
Screen('Flip',mainWindow, INSTANT);
WaitSecs(5); 
x = 0; 
while (x < .75) x=axis(joy, 1); end

%instructions for 1 blocker
instruct = ['When faced with a single blocker, your three options are:'...
    '\n\n  1.    Hit the ball towards the defender on the same side of the court as you.'...
    '\n\n  2.    Hit the ball towards the center defender.' ...
    '\n\n  3.    Hit the ball towards the defender on the opposite side of the court as you.'...
    '\n\n The joystick movements associated with each of these three options are shown below. '...
    'Notice the movements are flipped depending on which side of the court you are starting from!'];
DrawFormattedText(mainWindow,instruct,intro_textRow,intro_textRow,COLORS.MAINFONTCOLOR,WRAPCHARS*1.2);
Screen('DrawTexture', mainWindow,class_intro_texture,[0 0 intro_PICDIMS],[intro_topLeft intro_topLeft+intro_PICDIMS.*intro_RESCALE_FACTOR]);
cont = ['-- move the joystick RIGHT to continue --'];
DrawFormattedText(mainWindow,cont,'center',cont_textRow,COLORS.MAINFONTCOLOR,WRAPCHARS);
Screen('Flip',mainWindow, INSTANT);
WaitSecs(5); 
x = 0; 
while (x < .75) x=axis(joy, 1); end

%instructions for 2 blocker
instruct = ['When faced with two blockers, however, these options are no longer available, so the choices change accordingly! In this case, the three options are:'...
    '\n\n  1.    Hit the ball off the blockers hands away from the court (in volleyball, it?s a point if they touch it!).'...
    '\n\n  2.    Gently tip the ball straight over the blockers.'...
    '\n\n  3.    Hit the ball inside the blockers toward the defender on the other side of the court.'...
    '\n\n The joystick movements associated with each of these three options are shown below.'];   
DrawFormattedText(mainWindow,instruct,intro_textRow,intro_textRow,COLORS.MAINFONTCOLOR,WRAPCHARS*1.2);
Screen('DrawTexture', mainWindow,twoBlocker_texture,[0 0 intro_PICDIMS],[intro_topLeft intro_topLeft+intro_PICDIMS.*intro_RESCALE_FACTOR]);
instruct2 = ['In this scenario, the joystick movements are much sharper, in that you should not push the joystick all the way forward. '...
    'How far vertically you move the joystick is just as important as horizontally! ' ...
    'Again, notice the movements are flipped depending on which side of the court you are starting from!'];
DrawFormattedText(mainWindow,instruct2,intro_textRow,cont_textRow*.8,COLORS.MAINFONTCOLOR,WRAPCHARS*1.2);
cont = ['-- move the joystick RIGHT to continue --'];
DrawFormattedText(mainWindow,cont,'center',cont_textRow,COLORS.MAINFONTCOLOR,WRAPCHARS);
Screen('Flip',mainWindow, INSTANT);
WaitSecs(5); 
x = 0; 
while (x < .75) x=axis(joy, 1); end

% back to explaining
Screen('TextSize',mainWindow,MAINFONTSIZE);
instruct = ['When presented with each scenario, you will have 4 seconds to process '...
    'the image and think about what your response will be. Remember to look at the color '... 
    'jersey the opponent team is wearing-  what color team you are playing matters! '... 
    'Different opponents will have different skill-sets, meaning that the best response for '... 
    'one color team may not be the same for a different color team.'...
    '\n\n During this 4 second window, you should think about what '...
    'movement you will make, but do not move the joystick yet. After the 4 seconds are up, '...
    'you will then be given a "GO" cue, after which you will have 2 seconds to make your movement. '...
    'Move and HOLD the joystick in the position you want until the 2 seconds are up!'...
    '\n\n -- move the joystick RIGHT to continue --'];

DrawFormattedText(mainWindow,instruct,'center','center',COLORS.MAINFONTCOLOR,WRAPCHARS);
Screen('Flip',mainWindow, INSTANT);
intro_press4 = waitForKeyboard(trigger,device);
instruct = ['You will then be shown the outcome of your decision. The "best" choice will earn you one point most of the time, '...
    'while the other choices will only earn you a point a small percent of the time. '...
    'Choices that earned a point will be highlighted in green, '...
    'and choices that did not earn you a point will be highlighted in red. '...
    '\n\n \n\n If you do not pick one of three proper response options for the specific scenario presented, you will be given a recap of the response options, '...
    'and you will not earn any points. At the end of the study, you will earn cash proportional to how many points you finish with, '...
    'so make sure to try your best!'...
    '\n\n -- move the joystick RIGHT to continue --'];
DrawFormattedText(mainWindow,instruct,'center','center',COLORS.MAINFONTCOLOR,WRAPCHARS);
Screen('Flip',mainWindow, INSTANT);
WaitSecs(5); 
x = 0; 
while (x < .75) x=axis(joy, 1); end

%save intro data
matlabSaveFile = ['DATA_' num2str(SUBJECT) '_' num2str(SESSION) '_' num2str(ROUND) '_' datestr(now,'ddmmmyy_HHMM') '.mat'];
data_dir = fullfile(workingDir, 'BehavioralData');
if ~exist(data_dir,'dir'), mkdir(data_dir); end
ppt_dir = [data_dir filesep SUBJ_NAME filesep];
if ~exist(ppt_dir,'dir'), mkdir(ppt_dir); end

total_time = GetSecs - start_time;
save([ppt_dir matlabSaveFile],'SUBJ_NAME','total_time');  

end